### ISSUE TITLE
Dont Work

### ISSUE THREAD

**Issue by xmagcx** [bitnami/bitnami-docker-argo-cd#3]
### Name and Version

bitnami/argo-cd:latest

### What steps will reproduce the bug?
```console
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-argo-cd/master/docker-compose.yml > docker-compose.yml
docker-compose up -d
```
### What do you see instead?

when raising the image it does nothing, apparently, some instruction or service is missing

**Comment by carrodher** [comment]
This change should "solve" the issue: https://github.com/bitnami/bitnami-docker-argo-cd/commit/c07693475a8fa056fed8be5abdcffd65d956114d

I quoted solve because the container is not going to continue living since it just execute `argocd --help`, you need to override the command in order to execute any other action.
